@extends('admin.layouts.master')

@push('addon-css')
  <style>
    .modal-custom {
      z-index: 9999;
      top: 0px;
      left: 0px;
      margin: 0 auto;
      padding: 15px;
      position: fixed;
      width: 100vw;
      height: 100%;
      overflow: scroll;
      background: white;
    }

    .scale-in-center {
      -webkit-animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
      animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }

    /* ----------------------------------------------
     * Generated by Animista on 2023-2-18 16:21:10
     * Licensed under FreeBSD License.
     * See http://animista.net/license for more info.
     * w: http://animista.net, t: @cssanimista
     * ---------------------------------------------- */

    /**
     * ----------------------------------------
     * animation scale-in-center
     * ----------------------------------------
     */
    @-webkit-keyframes scale-in-center {
      0% {
        -webkit-transform: scale(0);
        transform: scale(0);
        opacity: 1;
      }

      100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        opacity: 1;
      }
    }

    @keyframes scale-in-center {
      0% {
        -webkit-transform: scale(0);
        transform: scale(0);
        opacity: 1;
      }

      100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        opacity: 1;
      }
    }
  </style>
@endpush

@section('content')
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">{{ ucwords($title) }}</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Pengaturan</a></li>
            <li class="breadcrumb-item active">{{ ucwords($title) }}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fa-edit"></i>
                List Item {{ ucwords($title) }}
              </h3>
            </div>
            <div class="card-body">
              <div class="row mb-2">
                <div class="col-sm-12 col-md-3 col-lg-3 mb-2">
                  <button class="btn btn-block btn-outline-primary badge-pill" id="button-add-item">Tambah Item</button>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6 mb-2"></div>
                <div class="col-sm-12 col-md-3 col-lg-3 text-right mb-2">
                  <button class="btn btn-block btn-outline-danger badge-pill" data-toggle="modal" data-target="#trash"
                    id="trashButton">Tong Sampah
                    Kategori</button>
                </div>
              </div>
              <div class="table-responsive">
                <table class="table table-striped table-hover" id="table-category">
                  <thead class="table-primary">
                    <tr>
                      <th>#</th>
                      <th>Kategori</th>
                      <th>Keterangan</th>
                      <th>Status</th>
                      <th>Aksi</th>
                    </tr>
                  </thead>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <div id="modal-add-item-new" class="d-none">
    {{-- modal tambah item --}}
    @include('admin.extra-page.modal-add-item')
    {{-- end modal tambah item --}}
  </div>
@endsection

@push('addon-js')
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
  <!-- bs-custom-file-input -->
  <script src="{{ asset('temp-adm/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
  {{-- sweet alert --}}
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <!-- Summernote -->
  {{-- <script src="{{ asset('temp-adm/plugins/summernote/summernote-bs4.min.js') }}"></script> --}}
  <!-- include summernote css/js -->
  {{-- <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script> --}}
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

  {{-- ckeditor --}}
  {{-- <script src="//cdn.ckeditor.com/4.20.0/standard/ckeditor.js"></script> --}}
  <script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
  <script src="{{ asset('ckeditor/plugins/embed/plugin.js') }}"></script>
  <script src="{{ asset('ckeditor/plugins/colorbutton/plugin.js') }}"></script>
  <script src="{{ asset('ckeditor/plugins/panelbutton/plugin.js') }}"></script>


  <script src="{{ asset('js/category-management.js') }}"></script>
@endpush
