@extends('admin.layouts.master')

@push('addon-css')
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.2/css/jquery.dataTables.min.css">
  <style>
    /* :root {
                  --ck-z-default: 100;
                  --ck-z-modal: calc(var(--ck-z-default) + 999);
                } */

    .modal-custom {
      position: fixed;
      z-index: 1060;
      top: 0;
      left: 0;
      margin: 0 auto;
      width: 100%;
      height: 100%;
      overflow: scroll;
    }

    .scale-in-center {
      -webkit-animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
      animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }

    /* ----------------------------------------------
        * Generated by Animista on 2023-2-18 16:21:10
        * Licensed under FreeBSD License.
        * See http://animista.net/license for more info.
        * w: http://animista.net, t: @cssanimista
        * ---------------------------------------------- */

    /*
        * ----------------------------------------
        * animation scale-in-center
        * ----------------------------------------
        */
    @-webkit-keyframes scale-in-center {
      0% {
        -webkit-transform: scale(0);
        transform: scale(0);
        opacity: 1;
      }

      100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        opacity: 1;
      }
    }

    @keyframes scale-in-center {
      0% {
        -webkit-transform: scale(0);
        transform: scale(0);
        opacity: 1;
      }

      100% {
        -webkit-transform: scale(1);
        transform: scale(1);
        opacity: 1;
      }
    }
  </style>
@endpush

@section('content')
  <input type="hidden" id="category_id" value="{{ $category['id'] }}">
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">{{ ucwords($title) }}</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Pengaturan</a></li>
            <li class="breadcrumb-item active">{{ ucwords($title) }}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-header">
              <h3 class="card-title">
                <i class="fas fa-edit"></i>
                List Item {{ ucwords($title) }}
              </h3>
            </div>
            <div class="card-body">
              <div>
                <div class="card bordered">
                  <div class="card-header">
                    <div class="d-flex justify-content-between">
                      <h5 class="card-title">Tambah Item {{ ucwords($title) }}</h5>
                      {{-- <button class="close close-custom-modal">&times;</button> --}}
                    </div>
                  </div>
                  @include('admin.extra-page.form-add-item')
                </div>
              </div>
              <div class="row mb-2 mt-4">
                <div class="col-sm-12 col-md-3 col-lg-3 text-right mb-2">
                  <button class="btn btn-block btn-outline-danger badge-pill" data-toggle="modal" data-target="#trash"
                    id="trashButton" data-id="{{ $category['id'] }}"><i class="fas fa-dumpster pr-1"></i>Tong Sampah</button>
                </div>
              </div>
              <div class="table-responsive">
                <table class="table table-striped table-hover w-100" id="table-item-list">
                  <thead class="table-primary">
                    <tr>
                      <th>#</th>
                      <th>Judul</th>
                      <th>Kalimat Pendukung</th>
                      <th>Kalimat Pelengkap</th>
                      <th>Aktif</th>
                      <th>Aksi</th>
                    </tr>
                  </thead>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <div id="modal-trash-item" class="d-none">
    {{-- modal tambah item --}}
    @include('admin.extra-page.modal-trash-item')
    {{-- end modal tambah item --}}
  </div>
@endsection

@push('addon-js')
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
  <script src="https://cdn.datatables.net/1.13.2/js/jquery.dataTables.min.js"></script>

  <!-- bs-custom-file-input -->
  <script src="{{ asset('temp-adm/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
  {{-- sweet alert --}}
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  {{-- ckeditor --}}
  <script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
  <script src="{{ asset('ckeditor/plugins/embed/plugin.js') }}"></script>
  <script src="{{ asset('ckeditor/plugins/colorbutton/plugin.js') }}"></script>
  <script src="{{ asset('ckeditor/plugins/panelbutton/plugin.js') }}"></script>


  <script src="{{ asset('js/category-management.js') }}"></script>
  <script>
    @if ($message = Session::get('success'))
      Swal.fire({
        icon: 'success',
        title: 'Success',
        text: "{!! $message !!}",
      })
    @elseif ($message = Session::get('error'))
      Swal.fire({
        icon: 'error',
        title: 'Opps..',
        text: "{!! $message !!}",
      })
    @endif

    $(document).ready(function() {
      bsCustomFileInput.init();
    });
  </script>
@endpush
